spring.application.name=sosocial

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/sosocialdb
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.open-in-view=false

# JWT
jwt.secret=${JWT_SECRET:sosocial-not-that-secret}
jwt.expiration-hours=1

#Flyway
spring.flyway.enable=true